# Spring properties
spring:
  application:
    name: client # Service registers under this name
# HTTP Server
server:
  port: 9001   # HTTP (Tomcat) port
# Discovery Server Access
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:9090/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 5
    preferIpAddress: false